// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCensus.Manager.DAL.Context;

#nullable disable

namespace NetCensus.Manager.DAL.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20220417021055_AddsDateTime")]
    partial class AddsDateTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCensus.Manager.DAL.Entities.BasicStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AvaiableRam")
                        .HasColumnType("double");

                    b.Property<double>("AvaiableStorage")
                        .HasColumnType("double");

                    b.Property<string>("CpuUsage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTimeRegistered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddresses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MachineNickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TotalRam")
                        .HasColumnType("double");

                    b.Property<double>("TotalStorage")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("BasicStats");
                });
#pragma warning restore 612, 618
        }
    }
}
